volumes:
  db_data:

services:
  bot:
    image: kasyak999/ctypto_bot
    env_file: .env
    volumes:
      - db_data:/bot/db
    # stdin_open: true
    # tty: true
    command: >
      sh -c "python main.py -s"